# Generated by Django 4.0.6 on 2022-08-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingmodel',
            name='datecomplite',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='trackingmodel',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
