# Generated by Django 4.0.6 on 2022-08-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0002_trackingmodel_datecomplite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingmodel',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
