# Generated by Django 4.1 on 2022-08-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0005_personalaccount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalaccount',
            name='telegram_chat_id',
            field=models.IntegerField(default=False),
        ),
    ]
