# Generated by Django 4.1 on 2022-12-16 05:12

from django.db import migrations, models
import parsing.validators.check_url


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0008_remove_personalaccount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingmodel',
            name='linkproduct',
            field=models.URLField(max_length=250, validators=[parsing.validators.check_url.check_url]),
        ),
    ]
