# Generated by Django 4.1 on 2022-12-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feedbackmodel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='message',
            field=models.TextField(default=True),
        ),
    ]
