# Generated by Django 4.1 on 2022-12-16 13:55

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_feedbackmodel_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
